/**********************************************************************/
/* Author      : Haitham F. Hamdy                                     */
/* Date        : 09 Oct. 2020                                          */
/* Version     : V01                                                  */
/**********************************************************************/


#include "BIT_MATH.h"
#include "STD_TYPES.h"

#include "MAFIO_INTERFACE.h"
#include "MAFIO_PRIVATE.h"
#include "MAFIO_config.h"


void MAFIO_voidSelectPortEXTICR1(PORT_T MAFIO_portPORTID,MAFIO_EXTICR1_BITS_T MAFIO_BIT0,MAFIO_EXTICR1_BITS_T MAFIO_BIT1,MAFIO_EXTICR1_BITS_T MAFIO_BIT2,MAFIO_EXTICR1_BITS_T MAFIO_BIT3)
{
switch (MAFIO_portPORTID)
{
  case PORTA:
  CLR_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT0);
  CLR_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT3);
  break;
  case PORTB:
  SET_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT0);
  CLR_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT3);
  break;
  case PORTC:
  CLR_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT0);
  SET_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR1,MAFIO_BIT3);
  break;
}
}


void MAFIO_voidSelectPortEXTICR2(PORT_T MAFIO_portPORTID,MAFIO_EXTICR2_BITS_T MAFIO_BIT0,MAFIO_EXTICR2_BITS_T MAFIO_BIT1,MAFIO_EXTICR2_BITS_T MAFIO_BIT2,MAFIO_EXTICR2_BITS_T MAFIO_BIT3)
{
switch (MAFIO_portPORTID)
{
  case PORTA:
  CLR_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT0);
  CLR_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT3);
  break;
  case PORTB:
  SET_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT0);
  CLR_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT3);
  break;
  case PORTC:
  CLR_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT0);
  SET_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR2,MAFIO_BIT3);
  break;
}
}


void MAFIO_voidSelectPortEXTICR3(PORT_T MAFIO_portPORTID,MAFIO_EXTICR3_BITS_T MAFIO_BIT0,MAFIO_EXTICR3_BITS_T MAFIO_BIT1,MAFIO_EXTICR3_BITS_T MAFIO_BIT2,MAFIO_EXTICR3_BITS_T MAFIO_BIT3)
{
switch (MAFIO_portPORTID)
{
  case PORTA:
  CLR_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT0);
  CLR_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT3);
  break;
  case PORTB:
  SET_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT0);
  CLR_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT3);
  break;
  case PORTC:
  CLR_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT0);
  SET_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR3,MAFIO_BIT3);
  break;
}
}


void MAFIO_voidSelectPortEXTICR4(PORT_T MAFIO_portPORTID,MAFIO_EXTICR4_BITS_T MAFIO_BIT0,MAFIO_EXTICR4_BITS_T MAFIO_BIT1,MAFIO_EXTICR4_BITS_T MAFIO_BIT2,MAFIO_EXTICR4_BITS_T MAFIO_BIT3)
{
switch (MAFIO_portPORTID)
{
  case PORTA:
  CLR_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT0);
  CLR_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT3);
  break;
  case PORTB:
  SET_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT0);
  CLR_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT3);
  break;
  case PORTC:
  CLR_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT0);
  SET_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT1);
  CLR_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT2);
  CLR_BIT(MAFIO->MAFIO_EXTICR4,MAFIO_BIT3);
  break;
}
}



void MAFIO_voidSelectEXTIPin(PORT_T MAFIO_portPORTID, PIN_T MAFIO_pinPINID)
{
switch (MAFIO_pinPINID)
{
  case PIN0:
  MAFIO_voidSelectPortEXTICR1(MAFIO_portPORTID,EXTI0_0_EXTICR1,EXTI0_1_EXTICR1,EXTI0_2_EXTICR1,EXTI0_3_EXTICR1);
  break;
  case PIN1:
  MAFIO_voidSelectPortEXTICR1(MAFIO_portPORTID,EXTI1_0_EXTICR1,EXTI1_1_EXTICR1,EXTI1_2_EXTICR1,EXTI0_3_EXTICR1);
  break;
  case PIN2:
  MAFIO_voidSelectPortEXTICR1(MAFIO_portPORTID,EXTI2_0_EXTICR1,EXTI2_1_EXTICR1,EXTI2_2_EXTICR1,EXTI2_3_EXTICR1);
  break;
  case PIN3:
  MAFIO_voidSelectPortEXTICR1(MAFIO_portPORTID,EXTI3_0_EXTICR1,EXTI3_1_EXTICR1,EXTI3_2_EXTICR1,EXTI3_3_EXTICR1);
  break;
  case PIN4: MAFIO_voidSelectPortEXTICR2(MAFIO_portPORTID,EXTI4_0_EXTICR2,EXTI4_1_EXTICR2,EXTI4_2_EXTICR2,EXTI4_3_EXTICR2);
  break;
  case PIN5:
  MAFIO_voidSelectPortEXTICR2(MAFIO_portPORTID,EXTI5_0_EXTICR2,EXTI5_1_EXTICR2,EXTI5_2_EXTICR2,EXTI5_3_EXTICR2);
  break;
  case PIN6:
  MAFIO_voidSelectPortEXTICR2(MAFIO_portPORTID,EXTI6_0_EXTICR2,EXTI6_1_EXTICR2,EXTI6_2_EXTICR2,EXTI6_3_EXTICR2);
  break;
  case PIN7:
  MAFIO_voidSelectPortEXTICR2(MAFIO_portPORTID,EXTI7_0_EXTICR2,EXTI7_1_EXTICR2,EXTI7_2_EXTICR2,EXTI7_3_EXTICR2);
  break;
  case PIN8:
  MAFIO_voidSelectPortEXTICR3(MAFIO_portPORTID,EXTI8_0_EXTICR3,EXTI8_1_EXTICR3,EXTI8_2_EXTICR3,EXTI8_3_EXTICR3);
  break;
  case PIN9:
  MAFIO_voidSelectPortEXTICR3(MAFIO_portPORTID,EXTI9_0_EXTICR3,EXTI9_1_EXTICR3,EXTI9_2_EXTICR3,EXTI9_3_EXTICR3);
  break;
  case PIN10:
  MAFIO_voidSelectPortEXTICR3(MAFIO_portPORTID,EXTI10_0_EXTICR3,EXTI10_1_EXTICR3,EXTI10_2_EXTICR3,EXTI10_3_EXTICR3);
  break;
  case PIN11:
  MAFIO_voidSelectPortEXTICR3(MAFIO_portPORTID,EXTI11_0_EXTICR3,EXTI11_1_EXTICR3,EXTI11_2_EXTICR3,EXTI11_3_EXTICR3);
  break;
  case PIN12:
  MAFIO_voidSelectPortEXTICR4(MAFIO_portPORTID,EXTI12_0_EXTICR4,EXTI12_1_EXTICR4,EXTI12_2_EXTICR4,EXTI12_3_EXTICR4);
  break;
  case PIN13:
  MAFIO_voidSelectPortEXTICR4(MAFIO_portPORTID,EXTI13_0_EXTICR4,EXTI13_1_EXTICR4,EXTI13_2_EXTICR4,EXTI13_3_EXTICR4);
  break;
  case PIN14:
  MAFIO_voidSelectPortEXTICR4(MAFIO_portPORTID,EXTI14_0_EXTICR4,EXTI14_1_EXTICR4,EXTI14_2_EXTICR4,EXTI14_3_EXTICR4);
  break;
  case PIN15:
  MAFIO_voidSelectPortEXTICR4(MAFIO_portPORTID,EXTI15_0_EXTICR4,EXTI15_1_EXTICR4,EXTI15_2_EXTICR4,EXTI15_3_EXTICR4);
  break;

}

}
//////////////////EVENTOUT functions//////////


void MAFIO_voidSelectPortEVOUT(PORT_T MAFIO_portPORTID)
{
  switch (MAFIO_portPORTID)
  {
    case PORTA:
    CLR_BIT(MAFIO->MAFIO_EVCR,PORT_0_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PORT_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PORT_2_EVCR);
    break;
    case PORTB:
    SET_BIT(MAFIO->MAFIO_EVCR,PORT_0_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PORT_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PORT_2_EVCR);
    break;
    case PORTC:
    CLR_BIT(MAFIO->MAFIO_EVCR,PORT_0_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PORT_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PORT_2_EVCR);
    break;
  }
}

void MAFIO_voidSelectPinEVOUT(PIN_T MAFIO_pinPINID)
{
  switch (MAFIO_pinPINID)
  {
    case PIN0:
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN1:
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN2:
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN3:
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN4:
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN5:
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN6:
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN7:
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN8:
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN9:
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN10:
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN11:
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN12:
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN13:
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN14:
    CLR_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
    case PIN15:
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_0_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_1_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_2_EVCR);
    SET_BIT(MAFIO->MAFIO_EVCR,PIN_3_EVCR);
    break;
  }
}

void MAFIO_voidConfigEventOutput(STATE_EVOUT_T MAFIO_State,PORT_T MAFIO_portPORTID,PIN_T MAFIO_pinPINID)
{
  switch (MAFIO_State)
  {
    case enable:
    SET_BIT(MAFIO->MAFIO_EVCR,EVOE_EVCR);
    MAFIO_voidSelectPortEVOUT(MAFIO_portPORTID);
    MAFIO_voidSelectPinEVOUT(MAFIO_pinPINID);

    break;
    case disable:
    CLR_BIT(MAFIO->MAFIO_EVCR,EVOE_EVCR);

    break;
  }
}
